### ISSUE TITLE
Improve default directory/file layout

### ISSUE THREAD

**Issue by dubslow** [MersenneForum/MersenneForumAliquot#7]
Christian, continuing the theme I've mentioned in PMs, what do you think is the best way to layout the mfaliquot package, vs the live website folder, vs the scripts, vs the templates, vs the log directory? The refactor branch contains a speculative re-organizing, putting the scripts, templates and logs into the same directory with the (very bad) name `working_dir`, but I'm pretty sure there's some better way to do it, and since your the host, and an experienced sysadmin as far as I can tell, what's your opinion on the matter?

**Comment by ChristianBeer** [comment]
What I want to achieve as the operator of the scripts is a segregation of active (python scripts) and inactive parts (website). That's why I use separate user accounts (one for the scripts, one for the webserver) so if someone gets access via the webserver he/she can't manipulate the scripts to do malicious things. Therefor I give write access to the website folder to the script user but not the other way around. With that in mind here would be my choice:

- `scripts/` contains the 'main' scripts that are executable (since you go for a single configuration file this can go in here too)
- `scripts/modules/` contains the needed 'auxiliary' python scripts (what currently resides in `mfaliquot`) included by the main scripts, I'm not sure if this is possible if you still want to  package these as pypi packages
- `tests/` I'm fine with that as is
- `website/static/` Should contain all the static stuff needed in the htdocs directory (like images, js and static pages), this gets copied to the htdocs directory manually if needed
- `website/templates/` Contains the templates used by the scripts to generate `AllSeq.html` and `statistics.html` since they do not get copied to the htdocs directory
- `data/` Contains the dynamic files `AllSeq.json`, `statistics.json`, ... copied from the htdocs directory if needed (before an update or once a week)
- `log/` I like this dir on the toplevel to contain all the logs so it is easy access
- `cron/` This is a convenience directory need on the RKN server where I collected the shell scripts that call the actual python scripts because of the CentOS SCL magic that needs to happen. I could place those files in `scripts/` too but I would end up with two files that only differ in endings (this is not nice for tab completion)

**Comment by dubslow** [comment]
Could `scripts/modules/` be a symlink to `../mfaliquot/`, or similar linking/faking it solution? I do kinda want to leave it packageable, at least the `theory` part of `mfaliquot`, and if that part may as well include the rest as well

**Comment by ChristianBeer** [comment]
symlinking the modules directory should work. this could even be better when a packaged version is later added in another place.

**Comment by dubslow** [comment]
How does that ^ look?

**Comment by ChristianBeer** [comment]
Since 4fe9642 is basically what I wanted I'm ok with it.

**Comment by dubslow** [comment]
Do you want it merged to master before you update the web-rkn branch?

**Comment by ChristianBeer** [comment]
Yes please. But I might not update web-rkn-new until Christmas. Next week is going to be busy but I'll take my laptop with me during holidays. I might have some time between Christmas dinners.

**Comment by dubslow** [comment]
What about if I also created a `live/` dir with nothing but symlinks to `data/` and `website/static/`? Might make the `cp` scripts easier to maintain, and also makes it more immediately obvious to someone new to the project how exactly everything is related. Hmm maybe that means `data/` should be a subdir of `website/`, like renamed to e.g. `website/generated/` or something?

**Comment by ChristianBeer** [comment]
I merged from `otherlayout` and I'm satisfied with the directory setup now. So I'm closing this issue as it is resolved for me.
